apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ include "user-management.namespace" . }}
  labels:
    {{- include "user-management.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.config.datasourceUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.datasourceUsername | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.config.hibernateDdlAuto | quote }}
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: {{ .Values.config.hibernateDialect | quote }}
  JWT_EXPIRATION: {{ .Values.config.jwtExpiration | quote }}
  AWS_S3_BUCKET_NAME: {{ .Values.config.s3BucketName | quote }}
  AWS_S3_REGION: {{ .Values.config.s3Region | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
  SPRING_RABBITMQ_HOST: {{ .Values.config.rabbitmqHost | quote }}
  SPRING_RABBITMQ_PORT: {{ .Values.config.rabbitmqPort | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .Values.config.rabbitmqUsername | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.config.rabbitmqPassword | quote }}
