apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ include "user-management.namespace" . }}
  labels:
    {{- include "user-management.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  aws-access-key: {{ .Values.secrets.awsAccessKey | quote }}
  aws-secret-key: {{ .Values.secrets.awsSecretKey | quote }}
