apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ include "user-management.namespace" . }}
  labels:
    {{- include "user-management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "user-management.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
